### ISSUE TITLE
install.js trying to run passed the last file in manifestPaths

### ISSUE THREAD

**Issue by SirGouki** [smolgumball/bb-vue#9]
the install script runs until it hits 14/14 in the rewriteImports function, then returns an error complaining that it cant get an undefined file because its trying to go passed _testSandbox.js:

```
[home ~/]> run installvue.js
Running script with 1 thread(s), pid 1863 and args: [].
installvue.js: Installed: /vue/bitburner-vue/bin/rmDeep.js [1/14]
installvue.js: Installed: /vue/bitburner-vue/components/AppRoot.js [2/14]
installvue.js: Installed: /vue/bitburner-vue/components/CommandPalette.js [3/14]
installvue.js: Installed: /vue/bitburner-vue/components/RecentEvents.js [4/14]
installvue.js: Installed: /vue/bitburner-vue/components/StoreDisplay.js [5/14]
installvue.js: Installed: /vue/bitburner-vue/eventBus.js [6/14]
installvue.js: Installed: /vue/bitburner-vue/lib.js [7/14]
installvue.js: Installed: /vue/bitburner-vue/main.js [8/14]
installvue.js: Installed: /vue/bitburner-vue/orchestrator.js [9/14]
installvue.js: Installed: /vue/bitburner-vue/store.js [10/14]
installvue.js: Installed: /vue/bitburner-vue/ui.commands.js [11/14]
installvue.js: Installed: /vue/bitburner-vue/ui.js [12/14]
installvue.js: Installed: /vue/bitburner-vue/vueLoader.js [13/14]
installvue.js: Installed: /vue/bitburner-vue/_testSandbox.js [14/14]
installvue.js: ERROR: Exception while downloading https://raw.githubusercontent.com/smolgumball/bitburner-vue/main/undefined: null
```

not 100% certain what's causing, but I'll drop a line if I figure it out before a fix is made.  
I have NOT edited any of the code in the install.js, yet, aside from setting the folder to vue and editing some comments to remove un-necessary whitespace/ascii art, and adding the @param {NS} ns back in (which shouldn't effect the running of the code as it just provides auto completion for netscript calls.)

**Comment by SirGouki** [comment]
This can be solved by the following change:

```
if (i < manifestLength)
{
  installPath = joinPaths(prefixDirectory, installPath);
  await getFileFromGH(ns, repoPath, installPath);
  await ns.sleep(100);
  await rewriteImports(ns, installPath, manifestData.importRoot, prefixDirectory);
  ns.tprint(`Installed: ${installPath} [${Number(i) + 1}/${manifestLength}]`);
}
```
 at line 49.  Not sure why, but `for(let i in manifestData.manifestPaths)` is not the same as `for (let i = 0; i < manifestData.manifestPaths.length; i++)` when it should be.

Also your dashboard script is incompatible with https://steamcommunity.com/sharedfiles/filedetails/?id=2689036632
I have no idea what's causing it as the error states slice is undefined from the orchestrator. is this dashboard only compatible with .scripts and not .js scripts? (My hacknet node script runs just fine while running the dashboard, but as soon as I run the linked script the dashboard script crashes)

**Comment by smolgumball** [comment]
Hi @SirGouki, I'm not able to recreate this issue.

Can you please:

1. Visit https://danielyxie.github.io/bitburner/
2. Ensure your game is fully deleted / reset via Options -> Delete Game
    - _Make a backup first if you play the game through this URL!_
3. Follow the install process again
4. Let me know if it continues to fail

Because of your previous issue here on GitHub, I'm inclined to think there may be some prototype patching happening and it's letting loose weevils in the system, so to speak. I really can't stress enough that prototype patching is a very dangerous practice and I'd encourage you to avoid wherever possible.

**Comment by SirGouki** [comment]
Sorry, but no.  That wouldn't help because I'm running the steam version, and the edit I suggested solved the exact problem.  The prototype patching was resolved *before* you answered it, and wasn't even on my bitburner install until after I had this set up.  I should not have mentioned that here since its a different issue and forgot to remove it.

I think its too much to ask to have to 100% start over a game for something like this, as opposed to solving the problem.  Given that the last one was a problem caused by a different script doing something it likely shouldn't have been doing, it'd be understandable to close that issue as not going to fix, since its not the fault of your code (and at the time I had no idea that was the problem)  However, causing an index out of bounds, getting it reported, and trying to blame it on something unrelated is very questionable.

**Comment by smolgumball** [comment]
Hiya @SirGouki, looks like we might be misunderstanding each-other a bit. I'm not suggesting that you start over from scratch, or that you play the game through the web version, but am instead seeking a reproduction of the issue. The web version of the game serves as a neutral, baseline environment in which issues can be recreated and verified with minimal effort.

Since I am not able to reproduce the issue myself, I can't do much to fix it. I understand that your changes to the source may have resolved the issue _for you_, but without reproducing the issue and then verifying the fix in a neutral environment, we simply can't be sure that the issue lies in the installer script itself.
